version: "3.7"
services:
  vault-service:
    container_name: vault
    image: vault:1.13.3
    depends_on: 
      - postgres-service
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    secrets:
      - vault_token
    cap_add:
      - IPC_LOCK
    networks:
      - default

  vault-prepopulate:
    image: vault:1.13.3
    depends_on:
      - vault-service
    volumes:
      - ./prepopulate_vault.sh:/usr/local/bin/prepopulate_vault.sh
    command: ["sh", "-c", "/usr/local/bin/prepopulate_vault.sh"]
    networks:
      - default

  postgres-service:
    container_name: postgres
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    secrets:
      - vault_token
      - postgres_passwd

    networks: 
      - default
  
  secret_consumer:
    image: secret_consumer:latest
    depends_on: 
      - vault-prepopulate
    environment: 
      VAULT_TOKEN: /run/secrets/vault_token
      VAULT_ADDR: vault-service
      POSTGRES_ADDR: postgres-service
    secrets:
      - vault_token
    networks: 
      - default

networks:
  default:
    name: vaultnetwork
    driver: bridge
secrets:
  vault_token:
    file: vault_token.txt
  postgres_passwd:
    file: postgres_passwd.txt
  
